go_library(
    name = "format",
    srcs = ["format.go"],
    deps = [
        "//src/parse/asp",
        "//src/core",
        "//src/cli",
        "//src/fs",
        "//third_party/go:logging",
        "//third_party/go:shlex",
    ],
    visibility = ["PUBLIC"],
)
