go_binary(
    name = "elan",
    srcs = ["main.go"],
    deps = [
        "//src/cli",
        "//tools/mettle/mettle",
        "//third_party/go:logging",
        "//third_party/go/prometheus",
    ],
)
