go_binary(
    name = "mettle",
    srcs = ["main.go"],
    deps = [
        "//src/cli",
        "//tools/mettle/worker",
        "//tools/mettle/api",
        "//third_party/go:logging",
        "//third_party/go/prometheus",
    ],
)
