grpc_library(
    name = "remote",
    srcs = ["remote.proto"],
    languages = ["go"],
    visibility = ["PUBLIC"],
)

grpc_library(
    name = "fs",
    srcs = ["fs.proto"],
    languages = ["go"],
    visibility = ["PUBLIC"],
)
