go_binary(
    name = 'parser',
    srcs = ['main.go'],
    deps = [
        '//src/cli',
        '//src/core',
        '//src/parse/participle',
        '//third_party/go:logging',
        '//third_party/go:participle',
    ],
)
