cc_test(
    name = 'subrepo_test',
    srcs = ['subrepo_test.cc'],
    deps = [
        '@third_party/cc/com_google_googletest//:gtest',
        '@third_party/cc/com_google_googletest//:gtest_main',
    ],
)
