version: 2
jobs:
   build:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please_ubuntu:latest
     steps:
       - checkout
       - run:
           name: Bootstrap & Build
           command: ./bootstrap.sh -p --test_results_file plz-out/results/test_results.xml
       - store_test_results:
           path: plz-out/results/test_results.xml
       - run:
           name: Package
           command: |
             ./plz-out/bin/src/please build -p //package:all &&
             mkdir /tmp/artifacts &&
             mv plz-out/gen/package/*.deb plz-out/gen/package/*.tar.gz /tmp/artifacts
       - store_artifacts:
           path: /tmp/artifacts
