go_library(
    name = "fsclient",
    srcs = ["client.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/grpcutil",
        "//third_party/go:grpc",
        "//third_party/go:multierror",
    ],
)
