name: "Please cache retrieval"
description: "Caches & retrieves parts of the plz cache between runs"
inputs:
  machine:
    required: false
    description: "The type of machine we're running on"
    default: ${{ github.job }}
runs:
  using: "composite"
  steps:
    - name: Cache retrieval
      uses: actions/cache@v3
      with:
        path: .plz-cache
        key: plz-${{ inputs.machine }}-${{ hashFiles('third_party/go/BUILD', 'third_party/python/BUILD', 'third_party/java/BUILD', '.github/workflows/build_test.yml') }}
        restore-keys: plz-${{ inputs.machine }}-
