plugin_repo(
    name = "go",
    plugin = "go-rules",
    owner = "peterebden",
    revision = "197bf5bf8d965e929c224f4f52bc716e942c7a52",
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.1.1",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    revision = "v1.2.4",
)
