plugin_repo(
    name = "go",
    plugin = "go-rules",
    owner = "peterebden",
    revision = "81027c5a77e64c549a706a12d3101615dcb94707",
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.1.1",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    revision = "v1.2.4",
)
