plugin_repo(
    name = "go",
    plugin = "go-rules",
    revision = "063f0bed39436b4112b4bb179e89d951a537015d",
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision = "v0.3.2",
)

plugin_repo(
    name = "shell",
    plugin = "shell-rules",
    revision = "v0.1.1",
)

plugin_repo(
    name = "python",
    plugin = "python-rules",
    revision = "v1.2.4",
)
