go_library(
    name = "grpc",
    srcs = ["grpc.go"],
    deps = [
        "//src/grpcutil",
        "//third_party/go:grpc",
        "//third_party/go:logging",
        "//tools/elan/storage",
    ],
)
