go_binary(
    name = "elan",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/cli",
        "//src/remote/proto:remote",
        "//third_party/go:logging",
        "//tools/elan/elan",
    ],
)
