go_library(
    name = "remote",
    srcs = ["remote.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//src/core",
        "//src/remote/proto:remote",
        "//third_party/go:grpc",
        "//third_party/go:grpc-middleware",
        "//third_party/go:logging",
    ],
)
