name: Build & Test
on: [push, pull_request]
env:
  PLZ_ARGS: "-p --profile ci"
jobs:
  alpine:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please_alpine:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/actions/plz-cache
      - name: Mark Git directory
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: Bootstrap & Build
        run: ./bootstrap.sh --test_results_file plz-out/results/please/test_results.xml
        env:
          PLZ_ARGS: "-p --profile ci --profile alpine --exclude no-musl"
      - uses: ./.github/actions/plz-logs
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please_ubuntu:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          cache: true
      - uses: ./.github/actions/plz-cache
      - name: Bootstrap & Build
        run: ./bootstrap.sh
      - name: No plugins
        run: plz-out/bin/src/please build //package:installed_files && ./test.sh --profile noplugins --test_results_file plz-out/results/please/no_plugin.xml
      - name: Package
        run: plz-out/bin/src/please build //package:signer //tools/misc:gen_release //docs:tarball //docs:deep-tarball //tools/performance:all -p
      - name: FreeBSD cross-compile
        run: plz-out/bin/src/please build --arch freebsd_amd64 //package:release_files
      # TODO(peterebden): Persist artifacts to be retrieved later for release
      - uses: ./.github/actions/plz-logs
  ubuntu_alt:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please_ubuntu_alt:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true
      - uses: ./.github/actions/plz-cache
      - name: Bootstrap & Build
        run: ./bootstrap.sh
      - uses: ./.github/actions/plz-logs
  darwin:
    runs-on: macos-latest
    needs: [ubuntu, ubuntu_alt, alpine]  # Doesn't really need them but no point doing the expensive macos run if the linux ones fail
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          cache: true
      - uses: ./.github/actions/plz-cache
      - name: Bootstrap & Build
        run: ./bootstrap.sh
      - name: Package
        run: plz-out/bin/src/please build //package:release_files
      - name: Cross-compile arm64
        run: plz-out/bin/src/please build  --arch darwin_arm64 -o go.cgoenabled:1 -o go.cgocctool:clang -o "go.cflags:-target arm64-apple-macos11" //package:release_files
      - uses: ./.github/actions/plz-logs
