name: Build & Test
on: [push, pull_request]
env:
  PLZ_ARGS: "-p --profile ci"
jobs:
  alpine:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please_alpine:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Plz cache
        uses: ./.github/actions/plz-cache
      - name: Mark Git directory
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: Bootstrap & Build
        run: ./bootstrap.sh --test_results_file plz-out/results/please/test_results.xml
        env:
          PLZ_ARGS: "-p --profile ci --profile alpine --exclude no-musl"
      - name: Package
        run: plz-out/bin/src/please build //package:all -p --profile ci --profile alpine
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plz-linux
          path: plz-out/bin/src/please
      - name: Store release artifacts
        uses: ./.github/actions/plz-artifacts
      - name: Archive logs
        uses: ./.github/actions/plz-logs
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please_ubuntu:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          cache: true
      - name: Plz cache
        uses: ./.github/actions/plz-cache
      - name: Bootstrap & Build
        run: ./bootstrap.sh
      - name: No plugins
        run: plz-out/bin/src/please build //package:installed_files && ./test.sh --profile noplugins --test_results_file plz-out/results/please/no_plugin.xml
      - name: Archive logs
        uses: ./.github/actions/plz-logs
  ubuntu_alt:
    runs-on: ubuntu-latest
    container:
      image: thoughtmachine/please_ubuntu_alt:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true
      - name: Plz cache
        uses: ./.github/actions/plz-cache
      - name: Bootstrap & Build
        run: ./bootstrap.sh
      - name: Archive logs
        uses: ./.github/actions/plz-logs
  darwin:
    runs-on: macos-latest
    needs: [ubuntu, ubuntu_alt, alpine]  # Doesn't really need them but no point doing the expensive macos run if the linux ones fail
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          cache: true
      - name: Plz cache
        uses: ./.github/actions/plz-cache
      - name: Bootstrap & Build
        run: ./bootstrap.sh
        # TODO(peterebden): Remove this after we excise plugin-specific tests from the central repo
        env:
          PLZ_ARGS: "--exclude py"
      - name: Package
        run: plz-out/bin/src/please build //package:release_files
      - name: Cross-compile arm64
        run: plz-out/bin/src/please build  --arch darwin_arm64 -o go.cgoenabled:1 -o go.cgocctool:clang -o "go.cflags:-target arm64-apple-macos11" //package:release_files
      - name: Store release artifacts
        uses: ./.github/actions/plz-artifacts
      - name: Archive logs
        uses: ./.github/actions/plz-logs
  freebsd:
    runs-on: ubuntu-latest
    needs: [alpine]
    container:
      image: thoughtmachine/please_ubuntu:20220803
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Plz cache
        uses: ./.github/actions/plz-cache
      - name: Retrieve artifacts
        uses: ./.github/actions/plz-download-artifacts
      - name: FreeBSD cross-compile
        run: ./please build --arch freebsd_amd64 //package:release_files
      - name: Store release artifacts
        uses: ./.github/actions/plz-artifacts
      - name: Archive logs
        uses: ./.github/actions/plz-logs
